# Generated by Django 4.2.1 on 2023-05-26 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_remove_movie_rating'),
        ('rating', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie.movie', verbose_name='Movie'),
            preserve_default=False,
        ),
    ]
