# Generated by Django 4.2.1 on 2023-05-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_alter_rating_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=3, max_length=10, verbose_name='Score'),
        ),
    ]
