# Generated by Django 4.2.1 on 2023-05-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('release_date', models.DateField(verbose_name='Release Date')),
                ('genre', models.CharField(max_length=100, verbose_name='Genre')),
                ('plot', models.TextField(verbose_name='Plot')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
